<div style=" background-color: RGB(0,114,200);" >
<h1 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">PROJET 4 DATA ANALYST</h1>
<h2 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">Réalisez une étude de santé publique avec R ou Python
</h2>
</div>

# OBJECTIF DE CE NOTEBOOK

Bienvenue dans l'outil plébiscité par les analystes de données Jupyter.

Il s'agit d'un outil permettant de mixer et d'alterner codes, textes et graphique.

Cet outil est formidable pour plusieurs raisons:

+ il permet de tester des lignes de codes au fur et à mesure de votre rédaction, de constater immédiatement le résultat d'un instruction, de la corriger si nécessaire.
+ De rédiger du texte pour expliquer l'approche suivie ou les résultats d'une analyse et de le mettre en forme grâce à du code html ou plus simple avec **Markdown**
+ d'agrémenter de graphiques

Pour vous aider dans vos premiers pas à l'usage de Jupyter et de Python, nous avons rédigé ce notebook en vous indiquant les instructions à suivre.

Il vous suffit pour cela de saisir le code Python répondant à l'instruction donnée.

Vous verrez de temps à autre le code Python répondant à une instruction donnée mais cela est fait pour vous aider à comprendre la nature du travail qui vous est demandée.

Et garder à l'esprit, qu'il n'y a pas de solution unique pour résoudre un problème et qu'il y a autant de résolutions de problèmes que de développeurs ;)...

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.1 - Importation des librairies</h3>
</div>

In [2]:
#Importation de la librairie Pandas
import pandas as pd

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.2 - Chargement des fichiers Excel</h3>
</div>

In [3]:
#Importation du fichier population.csv
population = pd.read_csv('population.csv')

#Importation du fichier dispo_alimentaire.csv
dispo_alimentaire = pd.read_csv('dispo_alimentaire.csv')

#Importation du fichier aide_alimentaire.csv
aide_alimentaire = pd.read_csv('aide_alimentaire.csv')

#Importation du fichier sous_nutrition.csv
sous_nutrition = pd.read_csv('sous_nutrition.csv')

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2 - Analyse exploratoire des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.1 - Analyse exploratoire du fichier population</h3>
</div>

In [4]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(population.shape[0]))
print("Le tableau comporte {} colonne(s)".format(population.shape[1]))

Le tableau comporte 1416 observation(s) ou article(s)
Le tableau comporte 3 colonne(s)

In [5]:
#Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(population.shape[1]))
#La nature des données dans chacune des colonnes
#Le nombre de valeurs présentes dans chacune des colonnes
population.info()

Le tableau comporte 3 colonne(s)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1416 entries, 0 to 1415
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Zone    1416 non-null   object
 1   Année   1416 non-null   int64
 2   Valeur  1416 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 33.3+ KB

In [6]:
#Affichage les 5 premières lignes de la table
population.head()

          Zone  Année     Valeur
0  Afghanistan   2013  32269.589
1  Afghanistan   2014  33370.794
2  Afghanistan   2015  34413.603
3  Afghanistan   2016  35383.032
4  Afghanistan   2017  36296.113

In [7]:
#Nous allons harmoniser les unités. Pour cela, nous avons décidé de multiplier la population par 1000
#Multiplication de la colonne valeur par 1000
population['Valeur'] = population['Valeur']*1000

In [8]:
#changement du nom de la colonne Valeur par Population
population.rename(columns={'Valeur': 'Population'}, inplace=True)

In [9]:
#Affichage les 5 premières lignes de la table pour voir les modifications
population.head()

          Zone  Année  Population
0  Afghanistan   2013  32269589.0
1  Afghanistan   2014  33370794.0
2  Afghanistan   2015  34413603.0
3  Afghanistan   2016  35383032.0
4  Afghanistan   2017  36296113.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.2 - Analyse exploratoire du fichier disponibilité alimentaire</h3>
</div>

In [10]:
#Afficher les dimensions du dataset
print(f"Le tableau comporte {dispo_alimentaire.shape[0]} observation(s) ou article(s) et {dispo_alimentaire.shape[1]} colonnes.")

Le tableau comporte 15605 observation(s) ou article(s) et 18 colonnes.

In [11]:
#Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(dispo_alimentaire.shape[1]))

Le tableau comporte 18 colonne(s)

In [12]:
#Affichage des 5 premières lignes de la table
dispo_alimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN

In [13]:
#remplacement des NaN dans le dataset par des 0
dispo_alimentaire.fillna(0, inplace=True)

In [14]:
#multiplication de toutes les lignes contenant des milliers de tonnes en Kg
liste_colonnes = dispo_alimentaire.columns.tolist() # on crée une liste avec tous les noms de colonnes
liste_non_modifie = ["Zone", "Produit", "Origine", "Disponibilité alimentaire (Kcal/personne/jour)", "Disponibilité alimentaire en quantité (kg/personne/an)", "Disponibilité de matière grasse en quantité (g/personne/jour)", "Disponibilité de protéines en quantité (g/personne/jour)"] # on crée une liste avec tous les noms de colonnes qu'on ne souhaite pas modifier

colonnes_a_modifier = list(set(liste_colonnes) - set(liste_non_modifie)) # on fait la différence entre les 2 pour avoir uniquement la liste des colonnes à modifier. On utilise l'opérateur '-' sur des sets de nos listes car plus rapide à traiter en python.

In [15]:
dispo_alimentaire[colonnes_a_modifier] *= (10**6) #conversion des colonnes concernées par 1 000 000 (millier de tonnes = million de kg)

In [16]:
#Affichage les 5 premières lignes de la table
dispo_alimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Analyse exploratoire du fichier aide alimentaire</h3>
</div>

In [17]:
#Afficher des dimensions du dataset
print(f"Le tableau comporte {aide_alimentaire.shape[0]} observation(s) ou article(s) et {aide_alimentaire.shape[1]} colonnes.")

Le tableau comporte 1475 observation(s) ou article(s) et 4 colonnes.

In [18]:
#Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(aide_alimentaire.shape[1]))

Le tableau comporte 4 colonne(s)

In [19]:
#Affichage les 5 premières lignes de la table
aide_alimentaire.head()

  Pays bénéficiaire  Année              Produit  Valeur
0       Afghanistan   2013  Autres non-céréales     682
1       Afghanistan   2014  Autres non-céréales     335
2       Afghanistan   2013         Blé et Farin   39224
3       Afghanistan   2014         Blé et Farin   15160
4       Afghanistan   2013             Céréales   40504

In [20]:
#changement du nom de la colonne Pays bénéficiaire par Zone
aide_alimentaire.rename(columns={'Pays bénéficiaire': 'Zone'}, inplace=True)

In [21]:
#Multiplication de la colonne Aide_alimentaire qui contient des tonnes par 1000 pour avoir des kg
aide_alimentaire['Valeur'] *= 1000

In [22]:
#Affichage les 5 premières lignes de la table
aide_alimentaire.head()

          Zone  Année              Produit    Valeur
0  Afghanistan   2013  Autres non-céréales    682000
1  Afghanistan   2014  Autres non-céréales    335000
2  Afghanistan   2013         Blé et Farin  39224000
3  Afghanistan   2014         Blé et Farin  15160000
4  Afghanistan   2013             Céréales  40504000

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Analyse exploratoire du fichier sous nutrition</h3>
</div>

In [23]:
#Afficher les dimensions du dataset
print(f"Le tableau comporte {sous_nutrition.shape[0]} observation(s) ou article(s) et {sous_nutrition.shape[1]} colonnes.")

Le tableau comporte 1218 observation(s) ou article(s) et 3 colonnes.

In [24]:
#Consulter le nombre de colonnes
print("Le tableau comporte {} colonne(s)".format(sous_nutrition.shape[1]))

Le tableau comporte 3 colonne(s)

In [25]:
#Afficher les 5 premières lignes de la table
sous_nutrition.head()

          Zone      Année Valeur
0  Afghanistan  2012-2014    8.6
1  Afghanistan  2013-2015    8.8
2  Afghanistan  2014-2016    8.9
3  Afghanistan  2015-2017    9.7
4  Afghanistan  2016-2018   10.5

In [26]:
#Conversion de la colonne sous nutrition en numérique
sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'])
# Il semble que la colonne comporte des valeurs qui ne sont pas des 'float' ('<0.1' par exemple ligne 60). Il faut donc utliser l'argument 'errors=coerce' pour forcer le changement de type.

ValueError: Unable to parse string "<0.1" at position 60

In [27]:
#Conversion de la colonne (avec l'argument errors=coerce qui permet de convertir automatiquement les lignes qui ne sont pas des nombres en NaN)
sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'], errors='coerce')
#Puis remplacement des NaN en 0
sous_nutrition['Valeur'].fillna(0)

0        8.6
1        8.8
2        8.9
3        9.7
4       10.5
        ...
1213     0.0
1214     0.0
1215     0.0
1216     0.0
1217     0.0
Name: Valeur, Length: 1218, dtype: float64

In [28]:
#changement du nom de la colonne Valeur par sous_nutrition
sous_nutrition.rename(columns={'Valeur': 'sous_nutrition'}, inplace=True)

In [29]:
#Multiplication de la colonne sous_nutrition par 1000000
sous_nutrition['sous_nutrition'] *= (10**6)

In [30]:
#Afficher les 5 premières lignes de la table
sous_nutrition.head()

          Zone      Année  sous_nutrition
0  Afghanistan  2012-2014       8600000.0
1  Afghanistan  2013-2015       8800000.0
2  Afghanistan  2014-2016       8900000.0
3  Afghanistan  2015-2017       9700000.0
4  Afghanistan  2016-2018      10500000.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.1 - Proportion de personnes en sous nutrition</h3>
</div>

In [33]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2017
# On va préparer le Dataframe sous_nutrition en modifiant la colonne année
intervalles_annees = sous_nutrition['Année'].unique()
intervalles_annees
# On s'assure qu'il n'y a que des intervalles de 3 ans dans le Dataframe

array([2013, 2014, 2015, 2016, 2017, 2018])

In [ ]:
sous_nutrition['Année'] = sous_nutrition['Année'].str.split('-',expand=True)[0].astype(int) + 1
# On récupère la première année de chaque cellule de la colonne 'Année' à laquelle on ajoute 1 pour obtenir l'année voulue (ex : 2016-2018 devient 2017 en int en plus !)

In [63]:
# On vérifie le dataset
sous_nutrition.head(7)

             Zone  Année  sous_nutrition
0     Afghanistan   2013       8600000.0
1     Afghanistan   2014       8800000.0
2     Afghanistan   2015       8900000.0
3     Afghanistan   2016       9700000.0
4     Afghanistan   2017      10500000.0
5     Afghanistan   2018      11100000.0
6  Afrique du Sud   2013       2200000.0

In [34]:
# création d'un dataset population pour 2017
population_2017 = population.loc[population['Année'] == 2017]
# création d'un dataset sous_nutrition pour 2017
sous_nutrition_2017 = sous_nutrition.loc[sous_nutrition['Année'] == 2017]

In [35]:
# On vérifie que les deux colonnes 'Zone' ont bien les mêmes données :
manquants_sous_nutrition = population_2017[~population_2017['Zone'].isin(sous_nutrition_2017['Zone'])]
# On cherche les pays qui ne sont PAS présents grâce à '~'.
manquants_population = sous_nutrition_2017[~sous_nutrition_2017['Zone'].isin(population_2017['Zone'])]
print(f"Pays dans population mais pas dans sous_nutrition: {len(manquants_sous_nutrition)}")
print(f"Pays dans sous_nutrition mais pas dans population: {len(manquants_population)}")

Pays dans population mais pas dans sous_nutrition: 33
Pays dans sous_nutrition mais pas dans population: 0

In [36]:
#Il y a donc des pays dans 'population' qui ne se retrouvent pas dans 'sous_nutrition'. En revanche, on a tous les pays de 'sous-nutrition' qui sont avec la même orthographe dans 'population'.
# On va donc faire la jointure à gauche sur 'sous-nutrition' car tous les pays ont des correspondances dans l'autre Dataframe et on veut observer la sous_nutrition en premier lieu.

In [37]:
# jointure entre les deux datasets crées
proportion_sous_nutrition_2017 = pd.merge(sous_nutrition_2017, population_2017, on=['Zone', 'Année'], how="left")

In [38]:
#Remplacement des NaN par des 0
proportion_sous_nutrition_2017.fillna(0, inplace=True)

In [39]:
#Affichage du dataset
display(proportion_sous_nutrition_2017)

                                       Zone  Année  sous_nutrition  Population
0                               Afghanistan   2017      10500000.0  36296113.0
1                            Afrique du Sud   2017       3100000.0  57009756.0
2                                   Albanie   2017        100000.0   2884169.0
3                                   Algérie   2017       1300000.0  41389189.0
4                                 Allemagne   2017             0.0  82658409.0
..                                      ...    ...             ...         ...
198  Venezuela (République bolivarienne du)   2017       8000000.0  29402484.0
199                                Viet Nam   2017       6500000.0  94600648.0
200                                   Yémen   2017             0.0  27834819.0
201                                  Zambie   2017             0.0  16853599.0
202                                Zimbabwe   2017             0.0  14236595.0

[203 rows x 4 columns]

In [40]:
#Calcul et affichage du nombre de personnes en état de sous nutrition
print("Le nombre de personnes en sous nutrition est de {} millions.".format(proportion_sous_nutrition_2017['sous_nutrition'].sum()/1000000)) # Division par 10**6 pour afficher le nombre en millions et rendre cela plus lisible.
print("Il y a {:.2f} milliards d'êtres humains sur terre.".format(proportion_sous_nutrition_2017['Population'].sum()/10**9)) #idem ici en milliards.
print("Cela représente une proportion de {:.2f}%.".format(proportion_sous_nutrition_2017['sous_nutrition'].sum()*100/proportion_sous_nutrition_2017['Population'].sum()))

Le nombre de personnes en sous nutrition est de 535.7 millions.
Il y a 7.54 milliards d'êtres humains sur terre.
Cela représente une proportion de 7.10%.

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.2 - Nombre théorique de personne qui pourrait être nourries</h3>
</div>

In [41]:
#Combien mange en moyenne un être humain ? Source => https://www.fao.org/4/y3557f/y3557f15.htm (en kcal/personne/j, moyenne mondiale)
nutrition_moyenne_par_jour = 2940

In [42]:
dispo_alimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0

In [43]:
#On commence par faire une jointure entre le dataframe population et dispo_alimentaire afin d'ajouter dans ce dernier la population
# On vérifie que les deux colonnes 'Zone' ont bien les mêmes données :
manquants_dispo_alimentaire = population_2017[~population_2017['Zone'].isin(dispo_alimentaire['Zone'])]
# On cherche les pays qui ne sont PAS présents grâce à '~'.
manquants_population =dispo_alimentaire[~dispo_alimentaire['Zone'].isin(population_2017['Zone'])]
print(f"Pays dans population mais pas dans dispo_alimentaire: {len(manquants_dispo_alimentaire)}")
print(f"Pays dans dispo_alimentaire mais pas dans population: {len(manquants_population)}")

Pays dans population mais pas dans dispo_alimentaire: 64
Pays dans dispo_alimentaire mais pas dans population: 189

In [44]:
# On observe les manquants de dispo_alimentaire
manquants_dispo_alimentaire['Zone'].unique()

array(['Andorre', 'Anguilla', 'Antilles néerlandaises (ex)', 'Aruba',
       'Bahreïn', 'Bhoutan', 'Bonaire, Saint-Eustache et Saba', 'Burundi',
       'Comores', 'Curaçao', 'Érythrée', 'Gibraltar', 'Groenland',
       'Guadeloupe', 'Guam', 'Guinée équatoriale', 'Guyane française',
       'Île de Man', 'Îles Anglo-Normandes', 'Îles Caïmanes', 'Îles Cook',
       'Îles Falkland (Malvinas)', 'Îles Féroé', 'Îles Mariannes du Nord',
       'Îles Marshall', 'Îles Turques-et-Caïques',
       'Îles Vierges américaines', 'Îles Vierges britanniques',
       'Îles Wallis-et-Futuna', 'Libye', 'Liechtenstein', 'Martinique',
       'Mayotte', 'Micronésie (États fédérés de)', 'Monaco', 'Montserrat',
       'Nauru', 'Nioué', 'Palaos', 'Palestine',
       'Papouasie-Nouvelle-Guinée', 'Porto Rico', 'Qatar',
       'République arabe syrienne', 'République démocratique du Congo',
       'Réunion', "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
       'Sahara occidental', 'Saint-Barthélemy',
       'Sainte-Hélène, Ascension et Tristan da Cunha', 'Saint-Marin',
       'Saint-Martin (partie française)', 'Saint-Pierre-et-Miquelon',
       'Saint-Siège', 'Samoa américaines', 'Seychelles', 'Singapour',
       'Sint Maarten  (partie néerlandaise)', 'Somalie', 'Soudan du Sud',
       'Tchéquie', 'Tokélaou', 'Tonga', 'Tuvalu'], dtype=object)

In [45]:
# On observe les manquants de population
manquants_population['Zone'].unique()

array(['Royaume-Uni', 'Tchéquie (la)'], dtype=object)

In [46]:
# On renomme les lignes de population pour qu'elles correspondent avec celles de dispo_alimentaire
population_2017.loc[population_2017['Zone'] == "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord", 'Zone'] = 'Royaume-Uni'
population_2017.loc[population_2017['Zone'] == "Tchéquie", 'Zone'] = 'Tchéquie (la)'

In [47]:
# On vérifie à nouveau
manquants_population = dispo_alimentaire[~dispo_alimentaire['Zone'].isin(population_2017['Zone'])]
print(f"Pays dans dispo_alimentaire mais pas dans population: {len(manquants_population)}")
#Tous les pays sont de dispo_alimentaire ont bien une correspondance dans population.

Pays dans dispo_alimentaire mais pas dans population: 0

In [48]:
# on peut maintenant ajouter la population au Dataframe dispo_alimentaire
dispo_alimentaire = pd.merge(dispo_alimentaire, population_2017, on='Zone', how="left")

In [52]:
#Affichage du nouveau dataframe
dispo_alimentaire

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Année,Population
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,0.0,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0,2017,36296113.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,2000000.0,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0,2017,36296113.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,2017,36296113.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017,36296113.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,0.0,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0,2017,36296113.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15600,Îles Salomon,Viande de Suides,animale,0.0,0.0,45.0,4.70,4.28,1.41,3000000.0,0.0,0.0,3000000.0,0.0,2000000.0,0.0,0.0,0.0,2017,636039.0
15601,Îles Salomon,Viande de Volailles,animale,0.0,0.0,11.0,3.34,0.69,1.14,2000000.0,0.0,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,2017,636039.0
15602,Îles Salomon,"Viande, Autre",animale,0.0,0.0,0.0,0.06,0.00,0.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017,636039.0
15603,Îles Salomon,Vin,vegetale,0.0,0.0,0.0,0.07,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017,636039.0
15604,Îles Salomon,"Épices, Autres",vegetale,0.0,0.0,4.0,0.48,0.21,0.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017,636039.0

In [53]:
#Création de la colonne dispo_kcal avec calcul des kcal disponibles mondialement
dispo_alimentaire['dispo_kcal par jour'] = dispo_alimentaire['Disponibilité alimentaire (Kcal/personne/jour)'] * dispo_alimentaire['Population']

In [54]:
dispo_alimentaire

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,...,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Année,Population,dispo_kcal par jour
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000000.0,...,0.0,53000000.0,0.0,53000000.0,0.0,0.0,0.0,2017,36296113.0,181480565.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000000.0,...,40000000.0,39000000.0,2000000.0,3000000.0,0.0,0.0,0.0,2017,36296113.0,36296113.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000000.0,...,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,2017,36296113.0,36296113.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017,36296113.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000000.0,...,82000000.0,82000000.0,0.0,0.0,0.0,0.0,0.0,2017,36296113.0,145184452.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15600,Îles Salomon,Viande de Suides,animale,0.0,0.0,45.0,4.70,4.28,1.41,3000000.0,...,0.0,3000000.0,0.0,2000000.0,0.0,0.0,0.0,2017,636039.0,28621755.0
15601,Îles Salomon,Viande de Volailles,animale,0.0,0.0,11.0,3.34,0.69,1.14,2000000.0,...,2000000.0,2000000.0,0.0,0.0,0.0,0.0,0.0,2017,636039.0,6996429.0
15602,Îles Salomon,"Viande, Autre",animale,0.0,0.0,0.0,0.06,0.00,0.04,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017,636039.0,0.0
15603,Îles Salomon,Vin,vegetale,0.0,0.0,0.0,0.07,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017,636039.0,0.0
15604,Îles Salomon,"Épices, Autres",vegetale,0.0,0.0,4.0,0.48,0.21,0.15,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017,636039.0,2544156.0

In [55]:
#Calcul du nombre d'humains pouvant être nourris
print("Il y a {:.2f} milliards d'êtres humains sur terre.".format(proportion_sous_nutrition_2017['Population'].sum()/10**9))
total_humains_nourris = round(dispo_alimentaire['dispo_kcal par jour'].sum() / nutrition_moyenne_par_jour)
print("Le nombre d'humains pouvant être nourris est de {:.2f} milliards.".format(total_humains_nourris/1000000000))
print("On peut donc nourrir {:.2f} % de la population mondiale.".format(100*total_humains_nourris/dispo_alimentaire.groupby(by='Zone')['Population'].mean().sum()))

Il y a 7.54 milliards d'êtres humains sur terre.
Le nombre d'humains pouvant être nourris est de 7.20 milliards.
On peut donc nourrir 97.77 % de la population mondiale.

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.3 - Nombre théorique de personne qui pourrait être nourrie avec les produits végétaux</h3>
</div>

In [56]:
#Transfert des données avec les végétaux dans un nouveau dataframe
dispo_alimentaire_vegetaux = dispo_alimentaire.loc[dispo_alimentaire['Origine'] == 'vegetale']

In [57]:
#Calcul du nombre de kcal disponible pour les végétaux
kcal_dispo_vegetaux_par_jour = dispo_alimentaire_vegetaux['dispo_kcal par jour'].sum()
kcal_dispo_vegetaux_par_jour

np.float64(17449509418936.0)

In [58]:
#Calcul du nombre d'humains pouvant être nourris avec les végétaux
total_humains_nourris_vegetaux = round(dispo_alimentaire_vegetaux['dispo_kcal par jour'].sum() / nutrition_moyenne_par_jour)
print("Le nombre d'humains pouvant être nourris avec les végétaux est de {:.2f} milliards.".format(total_humains_nourris_vegetaux/1000000000))
print("On peut donc nourrir {:.2f} % de la population mondiale avec des végétaux.".format(100*total_humains_nourris_vegetaux/dispo_alimentaire.groupby(by='Zone')['Population'].mean().sum()))

Le nombre d'humains pouvant être nourris avec les végétaux est de 5.94 milliards.
On peut donc nourrir 80.54 % de la population mondiale avec des végétaux.

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.4 - Utilisation de la disponibilité intérieure</h3>
</div>

In [59]:
#Calcul de la disponibilité totale
dispo_totale = dispo_alimentaire['Disponibilité intérieure'].sum()
print("La disponibilité totale est de  {} milliards de kg.".format(dispo_totale/(10**9)))

La disponibilité totale est de  9848.994 milliards de kg.

In [60]:
#création d'une boucle for pour afficher les différentes valeurs en fonction des colonnes aliments pour animaux, pertes, nourritures, 
liste_boucle = ['Aliments pour animaux', 'Pertes', 'Nourriture']

for elt in liste_boucle:
    (print(f"La Dispo de {elt} est de {dispo_alimentaire[elt].sum()/(10**9):.1f} milliards kg, cela représente {dispo_alimentaire[elt].sum()*100/dispo_totale:.2f}% de la dispo totale."))

La Dispo de Aliments pour animaux est de 1304.2 milliards kg, cela représente 13.24% de la dispo totale.
La Dispo de Pertes est de 453.7 milliards kg, cela représente 4.61% de la dispo totale.
La Dispo de Nourriture est de 4876.3 milliards kg, cela représente 49.51% de la dispo totale.

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.5 - Utilisation des céréales</h3>
</div>

In [61]:
#Création d'une liste avec toutes les variables
cereales = ['Avoine', 'Blé', 'Céréales, Autres', 'Maïs', 'Millet', 'Orge', 'Riz (Eq Blanchi)', 'Seigle', 'Sorgho']

In [ ]:
#Création d'un dataframe avec les informations uniquement pour ces céréales
masque_cereales = dispo_alimentaire['Produit'].isin(cereales)
dispo_cereales = dispo_alimentaire.loc[masque_cereales]
dispo_cereales

In [ ]:
#Affichage de la proportion d'alimentation animale
proportion_alim_animale = dispo_cereales['Aliments pour animaux'].sum()*100 / dispo_cereales['Disponibilité intérieure'].sum()
print("La proportion d'alimentation animale dans l'utilisation des céréales est de {:.2f}%.".format(proportion_alim_animale))

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.6 - Pays avec la proportion de personnes sous-alimentée la plus forte en 2017</h3>
</div>

In [ ]:
#Création de la colonne proportion par pays
proportion_sous_nutrition_2017['Proportion en %'] = proportion_sous_nutrition_2017['sous_nutrition']*100 / proportion_sous_nutrition_2017['Population']

In [ ]:
#affichage après trie des 10 pires pays
proportion_sous_nutrition_2017.sort_values('Proportion en %', ascending=False,  inplace=True)
proportion_sous_nutrition_2017.head(10)
#ajout graph

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.7 - Pays qui ont le plus bénéficié d'aide alimentaire depuis 2013</h3>
</div>

In [ ]:
#calcul du total de l'aide alimentaire par pays
total_aide_pays = aide_alimentaire.groupby('Zone')['Valeur'].sum().reset_index()
total_aide_pays

In [ ]:
#affichage après trie des 10 pays qui ont bénéficié le plus de l'aide alimentaire
total_aide_pays.sort_values(by='Valeur', ascending=False, inplace=True)
total_aide_pays.head(10)

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.8 - Evolution des 5 pays qui ont le plus bénéficiés de l'aide alimentaire entre 2013 et 2016</h3>
</div>

In [ ]:
#Création d'un dataframe avec la zone, l'année et l'aide alimentaire puis groupby sur zone et année
aide_alimentaire_evolution = aide_alimentaire[['Zone', 'Année', 'Valeur']]
aide_alimentaire_evolution = aide_alimentaire_evolution.groupby(['Zone', 'Année']).sum().reset_index()
aide_alimentaire_evolution

In [ ]:
#Création d'une liste contenant les 5 pays qui ont le plus bénéficiées de l'aide alimentaire
liste_top_5 = total_aide_pays['Zone'].head(5).tolist()
print(liste_top_5)

In [ ]:
#On filtre sur le dataframe avec notre liste
mask = aide_alimentaire_evolution['Zone'].isin(liste_top_5)
evolution_aide_top5 = aide_alimentaire_evolution.loc[mask]
evolution_aide_top5.info()

In [ ]:
# Affichage des pays avec l'aide alimentaire par année
import matplotlib.pyplot as plt

evolution_aide_top5.pivot(index='Année', columns='Zone', values='Valeur').plot(kind='line', marker='o')
plt.xticks([2013, 2014, 2015, 2016])
plt.title("Évolution de l'aide alimentaire pour le Top 5")
plt.ylabel("Quantité en centaines de millions")
plt.show()

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.9 - Pays avec le moins de disponibilité par habitant</h3>
</div>

In [ ]:
#Calcul de la disponibilité en kcal par personne par jour par pays
dispo_par_pays = dispo_alimentaire.groupby('Zone')['Disponibilité alimentaire (Kcal/personne/jour)'].sum().reset_index()
dispo_par_pays

In [ ]:
#Affichage des 10 pays qui ont le moins de dispo alimentaire par personne 
dispo_par_pays_asc = dispo_par_pays.sort_values(by='Disponibilité alimentaire (Kcal/personne/jour)', ascending=True)
dispo_par_pays_asc.head(10)

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.10 - Pays avec le plus de disponibilité par habitant</h3>
</div>

In [ ]:
#Affichage des 10 pays qui ont le plus de dispo alimentaire par personne 
dispo_par_pays_desc = dispo_par_pays.sort_values(by='Disponibilité alimentaire (Kcal/personne/jour)', ascending=False)
dispo_par_pays_desc.head(10)

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.11 - Exemple de la Thaïlande pour le Manioc</h3>
</div>

In [ ]:
#création d'un dataframe avec uniquement la Thaïlande 
df_thailande = dispo_alimentaire.loc[dispo_alimentaire['Zone'] == 'Thaïlande']
df_thailande

In [ ]:
#Calcul de la sous nutrition en Thaïlande
sous_nutrition_thai = proportion_sous_nutrition_2017.loc[proportion_sous_nutrition_2017['Zone'] == 'Thaïlande']
sous_nutrition_thai

In [ ]:
# On calcule la proportion exportée en fonction de la proportion
#filtrer sur thailande et manioc sur dispo alim

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 6 - Analyse complémentaires</h2>
</div>

In [ ]:
#ajouter en dessous toutes les analyses complémtaires