<div style="display: flex; background-color: RGB(255,114,0);" >
<h1 style="margin: auto; padding: 30px; ">ANALYSE DU STOCK ET DES VENTES DU SITE BOTTLENECK</h1>
</div>

# OBJECTIF DE CE NOTEBOOK

Bienvenue dans l'outil plébiscité par les analystes de données Jupyter.

Il s'agit d'un outil permettant de mixer et d'alterner code, texte et graphiques.

Cet outil est formidable pour plusieurs raisons:

+ Il permet de tester des lignes de codes au fur et à mesure de votre rédaction, de constater immédiatement le résultat d'une instruction, de la corriger si nécessaire.
+ Il permet aussi de rédiger du texte pour expliquer l'approche suivie ou les résultats d'une analyse et de le mettre en forme grâce à du code html ou plus simple avec **Markdown**
+ Il est possible d'ajouter des graphiques

Pour vous aider dans vos premiers pas à l'usage de Jupyter et de Python, nous avons rédigé ce notebook en vous indiquant les instructions à suivre.

Il vous suffit pour cela de saisir le code Python répondant à l'instruction donnée.

Vous verrez de temps à autre le code Python répondant à une instruction donnée mais cela est fait pour vous aider à comprendre la nature du travail qui vous est demandé.

Et gardez à l'esprit qu'il n'y a pas de solution unique pour résoudre un problème et qu'il y a autant de résolutions de problèmes que de développeurs ;)...

<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">1.1 - Importation des librairies</h3>
</div>

In [2]:
#Importation de la librairie Pandas
import pandas as pd

In [3]:
#Importation de la librairie plotly express
import plotly.express as px

In [4]:
#Trouver dans Google l'instruction permettant d'afficher toutes les colonnes d'un dataframe
#Saisir dans Google les mots clés "display all columns dataframe Pandas" par exemple.
#Dans les résultats de la recherche, privilégier les solutions provenant de Stack Overflow ou Medium

# https://stackoverflow.com/questions/49188960/how-to-show-all-columns-names-on-a-large-pandas-dataframe
pd.set_option('display.max_columns', None)

<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etapes 1 a 3 (automatisees) - Consolidation des donnees</h2>
</div>

Le chargement, le nettoyage et la fusion des 3 sources (ERP, extraction web, table de liaison) — realises manuellement dans la version initiale du notebook — sont desormais encapsules dans le script `consolidation_donnees.py` (cf. Livrable 4, section Reproductibilite). Le detail des regles de nettoyage appliquees (doublons, `sku` manquants, prix/stocks negatifs, articles hors vente, etc.) reste documente dans le Livrable 1 et dans le rapport d'anomalies genere ci-dessous a chaque execution.

In [5]:
from consolidation_donnees import consolider_donnees, afficher_rapport

df_merge, rapport = consolider_donnees("erp.xlsx", "web.xlsx", "liaison.xlsx")
afficher_rapport(rapport)
df_merge

/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

=== Rapport de consolidation des données Bottleneck ===
- erp prix negatifs supprimes : 3
- erp stocks negatifs corriges : 2
- erp hors vente exclus : 106
- erp doublons product id : 0
- web sku manquants exclus : 85
- web lignes non product exclues : 714
- web product type manquant exclus : 1
- web doublons sku : 0
- liaison doublons product id : 0
- liaison doublons id web : 0
- liaison id web manquants : 91
- product id dans liaison absents erp : 109
- product id dans erp absents liaison : 0
- id web dans web absents merge : 1
- id web dans merge absents web : 2
- lignes finales consolidees : 712

/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price
0,5794,Vin,Château Fonréaud Bordeaux Blanc Le Cygne 2016,5.0,15,21.70,10.65
1,5827,Vin,Agnès Levet Côte Rôtie Maestria 2017,2.0,4,55.00,29.55
2,4964,Vin,Château Turcaud Bordeaux Rouge Cuvée Majeure 2018,10.0,23,12.10,6.50
3,4223,Vin,Xavier Frissant Touraine Sauvignon 2019,15.0,42,9.70,4.81
4,5900,Vin,Stéphane Tissot Arbois D.D. 2016,7.0,21,18.25,8.96
...,...,...,...,...,...,...,...
707,4073,Vin,Château de Vaudieu Châteauneuf-du-Pape L'Avenu...,4.0,8,77.80,40.60
708,4198,Vin,Moulin de Gassac IGP Pays d'Hérault Guilhem Ro...,0.0,0,5.80,2.97
709,5630,Vin,Parés Baltà Penedès Electio 2013,10.0,23,28.00,14.61
710,5962,Vin,Camin Larredya Jurançon Moelleux Au Capcéu 2018,5.0,8,30.00,15.50
711,4261,Vin,Chermette Domaine du Vissoux Beaujolais Griott...,15.0,48,9.90,5.01

<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 4 - Analyse univariée des prix</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 4.1 - Exploration par la visualisation de données</h3>
</div>

In [6]:
#Autre méthode avec plotly express
fig = px.box(df_merge, y="price", title="Distribution des prix des produits", width=600, height=400)
fig.show()

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 4.2 - Exploration par l'utilisation de méthodes statistiques</h3>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 4.2.1 - Identification par le Z-index</h3>
</div>

In [7]:
#Calculer la moyenne du prix
#Calculer l'écart-type du prix

moyenne = df_merge['price'].mean()
ecart_type = df_merge['price'].std()
z_score = (df_merge['price']- moyenne) / ecart_type
print(f"La moyenne du prix est : {moyenne:.2f}, l'écart-type : {ecart_type:.2f}.")

La moyenne du prix est : 32.38, l'écart-type : 27.62.

In [8]:
#Calculer le Z-score (distance en écart-type d'une valeur par rapport à la moyenne)
df_merge['z__score'] = (df_merge['price']- moyenne) / ecart_type

In [9]:
#Quel est le seuil prix dont le z-score est supérieur à 3?
# On peut regarder le premier produit à partir duquel la valeur de z-score dépasse 3
df_merge[['price', 'z__score']][df_merge['z__score'] > 3].sort_values(by='z__score', ascending=True)

     price  z__score
302  116.4  3.042417
406  121.0  3.208989
629  121.0  3.208989
419  122.0  3.245200
153  124.8  3.346591
392  135.0  3.715945
226  137.0  3.788368
212  157.0  4.512591
210  175.0  5.164392
448  176.0  5.200603
319  191.3  5.754634
687  217.5  6.703367
597  225.0  6.974951

In [10]:
# Ou regarder la valeur de prix pour un z-score = 3
seuil = 3 * ecart_type + moyenne
print(f"le seuil pour un z-score à 3 est : {seuil:.2f}.")

le seuil pour un z-score à 3 est : 115.23.

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 4.2.2 - Identification par l'intervalle interquartile</h3>
</div>

In [11]:
#Utilisation de la fonction "describe" de Pandas pour l'étude des mesures de dispersion
df_merge.describe()

,product_id,total_sales,stock_quantity,price,purchase_price,z__score
count,712.000000,712.000000,712.000000,712.000000,712.000000,7.120000e+02
mean,5033.837079,8.047753,23.432584,32.381250,16.928427,-4.490790e-17
std,790.999404,4.161030,22.247577,27.615786,14.838586,1.000000e+00
min,3847.000000,0.000000,0.000000,5.200000,2.740000,-9.842649e-01
25%,4280.750000,5.000000,9.000000,14.087500,7.240000,-6.624381e-01
50%,4796.000000,8.000000,20.000000,23.450000,12.305000,-3.234110e-01
75%,5711.250000,11.000000,30.000000,42.125000,22.035000,3.528326e-01
max,7338.000000,36.000000,145.000000,225.000000,137.810000,6.974951e+00

In [12]:
#Définir un seuil pour les articles "outliers" en prix
# On calcule Q1 (25%) et Q3 (75%)
q1 = df_merge['price'].quantile(0.25)
q3 = df_merge['price'].quantile(0.75)

# On calcule l'IQR (l'écart entre les deux)
iqr = q3 - q1

seuil_haut = q3 + 1.5 * iqr

print(f"Le seuil de prix pour les articles outliers est de {seuil_haut:.2f}€.")

Le seuil de prix pour les articles outliers est de 84.18€.

In [13]:
#Définir le nombre d'articles et la proportion de l'ensemble du catalogue "outliers"

#Nombre d'outliers (ceux qui dépassent le seuil)
nb_outliers = len(df_merge[df_merge['price'] > seuil_haut])

#Calcul de la proportion (en pourcentage)
proportion_outliers = (nb_outliers / len(df_merge)) * 100

print(f"Nombre d'outliers détectés : {nb_outliers}")
print(f"Proportion des outliers : {proportion_outliers:.2f} %")

Nombre d'outliers détectés : 31
Proportion des outliers : 4.35 %

In [14]:
#Selon vous, ces outliers sont-ils justifiés ? Comment le démontrer si cela est possible ?
# Je soupconne que ce sont des spiritueux plus chers ou des vins de meilleurs qualité, pour cela il faut aller les regarder
outliers_ventes = df_merge[df_merge['price'] > seuil_haut].sort_values('price', ascending=False)
outliers_ventes

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price,z__score
597,4352,Champagne,Champagne Egly-Ouriet Grand Cru Millésimé 2008,11.0,0,225.0,137.81,6.974951
687,5001,Vin,David Duband Charmes-Chambertin Grand Cru 2014,2.0,18,217.5,116.87,6.703367
319,5892,Champagne,Coteaux Champenois Egly-Ouriet Ambonnay Rouge ...,6.0,98,191.3,116.06,5.754634
448,4402,Cognac,Cognac Frapin VIP XO,3.0,11,176.0,78.25,5.200603
210,5767,Vin,Camille Giroud Clos de Vougeot 2016,4.0,12,175.0,90.42,5.164392
212,4406,Cognac,Cognac Frapin Château de Fontpinot 1989 20 Ans...,4.0,12,157.0,69.08,4.512591
226,4904,Vin,Domaine Des Croix Corton Charlemagne Grand Cru...,3.0,9,137.0,67.95,3.788368
392,6126,Champagne,Champagne Gosset Célébris Vintage 2007,5.0,138,135.0,80.33,3.715945
153,5612,Vin,Domaine Weinbach Gewurztraminer Grand Cru Furs...,1.0,19,124.8,66.41,3.346591
419,5917,Whisky,Wemyss Malts Single Cask Scotch Whisky Choc 'n...,3.0,12,122.0,54.24,3.245200
406,6216,Vin,Domaine des Comtes Lafon Volnay 1er Cru Champa...,2.0,14,121.0,60.02,3.208989
629,6213,Vin,Domaine des Comtes Lafon Volnay 1er Cru Santen...,3.0,9,121.0,63.14,3.208989
302,6202,Vin,Domaine Clerget Echezeaux Grand Cru En Orveaux...,5.0,12,116.4,63.15,3.042417
144,6212,Vin,Domaine des Comtes Lafon Volnay 1er Cru Santen...,7.0,16,115.0,59.42,2.991722
337,6215,Vin,Domaine des Comtes Lafon Volnay 1er Cru Champa...,4.0,14,115.0,56.45,2.991722
442,5918,Whisky,Wemyss Malts Single Cask Scotch Whisky Chai Ca...,3.0,12,114.0,52.25,2.955511
547,5025,Champagne,Champagne Agrapart &amp; Fils L'Avizoise Extra...,6.0,136,112.0,68.60,2.883088
254,4582,Vin,Château de Meursault Puligny-Montrachet 1er Cr...,1.0,18,109.6,53.80,2.796181
307,4404,Cognac,Cognac Frapin Château de Fontpinot XO,4.0,17,108.5,52.22,2.756349
163,6201,Vin,David Duband Chambolle-Musigny 1er Cru Les Sen...,6.0,16,105.6,57.29,2.651337
53,5008,Vin,Domaine des Comtes Lafon Volnay 1er Cru Santen...,7.0,12,105.0,56.42,2.629610
124,5007,Vin,Domaine des Comtes Lafon Volnay 1er Cru Santen...,3.0,15,105.0,55.88,2.629610
85,4407,Cognac,Cognac Frapin Cigar Blend,5.0,14,104.0,46.71,2.593399
602,4903,Vin,Domaine Des Croix Corton Grand Cru Les Grèves ...,2.0,12,102.3,51.80,2.531840
630,4115,Vin,Zind-Humbrecht Riesling Grand Cru Rangen De Th...,1.0,12,100.0,52.70,2.448554
412,6214,Vin,Domaine des Comtes Lafon Volnay 1er Cru Champa...,6.0,9,99.0,49.62,2.412343
232,5916,Whisky,Wemyss Malts Single Cask Scotch Whisky Chocola...,1.0,1,93.0,40.49,2.195076
299,5565,Vin,Tempier Bandol Cabassaou 2017,1.0,0,92.0,46.11,2.158865
585,4132,Vin,Zind-Humbrecht Pinot Gris Grand Cru Rangen De ...,5.0,7,88.4,44.30,2.028505
691,5026,Champagne,Champagne Agrapart &amp; Fils Minéral Extra Br...,9.0,101,86.8,50.13,1.970567
217,4359,Champagne,Champagne Larmandier-Bernier Grand Cru Les Che...,7.0,112,85.6,51.93,1.927113

<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 5 - Analyse univariée du CA, des quantités vendues, des stocks et de la marge ainsi qu'une analyse multivariée  </h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.1 - Analyse des ventes en CA</h3>
</div>

In [15]:
##############################
# Calculer le CA du site web #
##############################

#Créer une colonne calculant le CA par article
df_merge['CA'] = df_merge['price'] * df_merge['total_sales']
#Calculer la somme de la colonne "ca_par_article"
somme_ca = df_merge['CA'].sum()
#Ce résultat correspond au chiffre d'affaire du site web
print(f"Le chiffre d'affaires total généré par le site web est de : {somme_ca:.2f} €")

Le chiffre d'affaires total généré par le site web est de : 143423.90 €

In [16]:
###############################
# Palmarès des articles en CA #
###############################

#Effectuer le tri dans l'ordre décroissant du CA du dataset df_merge
df_merge = df_merge.sort_values(by='CA', ascending=False)

In [17]:
#Réinitialiser l'index du dataset par un reset_index
df_merge = df_merge.reset_index(drop=True)

In [18]:
#Afficher les 20 premiers articles en CA
df_topCA = df_merge.head(20)
df_topCA

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price,z__score,CA
0,4352,Champagne,Champagne Egly-Ouriet Grand Cru Millésimé 2008,11.0,0,225.0,137.81,6.974951,2475.0
1,5892,Champagne,Coteaux Champenois Egly-Ouriet Ambonnay Rouge ...,6.0,98,191.3,116.06,5.754634,1147.8
2,4353,Champagne,Champagne Egly-Ouriet Grand Cru Brut Rosé,14.0,127,79.5,45.91,1.706225,1113.0
3,5826,Vin,Agnès Levet Côte Rôtie Améthyste 2017,20.0,34,41.2,21.71,0.319337,824.0
4,6212,Vin,Domaine des Comtes Lafon Volnay 1er Cru Santen...,7.0,16,115.0,59.42,2.991722,805.0
5,5026,Champagne,Champagne Agrapart &amp; Fils Minéral Extra Br...,9.0,101,86.8,50.13,1.970567,781.2
6,5008,Vin,Domaine des Comtes Lafon Volnay 1er Cru Santen...,7.0,12,105.0,56.42,2.629610,735.0
7,5767,Vin,Camille Giroud Clos de Vougeot 2016,4.0,12,175.0,90.42,5.164392,700.0
8,6126,Champagne,Champagne Gosset Célébris Vintage 2007,5.0,138,135.0,80.33,3.715945,675.0
9,5025,Champagne,Champagne Agrapart &amp; Fils L'Avizoise Extra...,6.0,136,112.0,68.60,2.883088,672.0
10,6201,Vin,David Duband Chambolle-Musigny 1er Cru Les Sen...,6.0,16,105.6,57.29,2.651337,633.6
11,4406,Cognac,Cognac Frapin Château de Fontpinot 1989 20 Ans...,4.0,12,157.0,69.08,4.512591,628.0
12,4647,Vin,Bernard Baudry Chinon Rouge La Croix Boissée 2017,22.0,45,28.5,14.14,-0.140545,627.0
13,4358,Champagne,Champagne Larmandier-Bernier Grand Cru Vieille...,8.0,81,77.0,47.16,1.615697,616.0
14,4359,Champagne,Champagne Larmandier-Bernier Grand Cru Les Che...,7.0,112,85.6,51.93,1.927113,599.2
15,6214,Vin,Domaine des Comtes Lafon Volnay 1er Cru Champa...,6.0,9,99.0,49.62,2.412343,594.0
16,6202,Vin,Domaine Clerget Echezeaux Grand Cru En Orveaux...,5.0,12,116.4,63.15,3.042417,582.0
17,4350,Champagne,Champagne Egly-Ouriet Grand Cru Extra Brut V.P.,7.0,145,79.5,47.30,1.706225,556.5
18,4573,Vin,Château de Meursault Beaune-Grèves Les Trois J...,8.0,12,67.2,36.46,1.260828,537.6
19,4402,Cognac,Cognac Frapin VIP XO,3.0,11,176.0,78.25,5.200603,528.0

In [19]:
#Graphique en barre des 20 premiers articles avec plotly express
fig = px.bar(df_topCA, 
             x='CA', 
             y='post_title', 
             color = 'product_type',
             width=1500,
             height=2000,
             title="Top 20 des articles par Chiffre d'Affaires",
             labels={'CA': 'Chiffre d\'Affaires (€)', 'post_title': 'Nom du produit'})

fig.update_layout(yaxis={'categoryorder':'total ascending'}, 
                  height=800)

fig.show()

In [20]:
#############################
# Calculer le 20 / 80 en CA #
#############################

#Créer une colonne calculant la part du CA de la ligne dans le dataset
df_merge['%CA'] = 100 * (df_merge['CA'] / df_merge['CA'].sum())
df_merge

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price,z__score,CA,%CA
0,4352,Champagne,Champagne Egly-Ouriet Grand Cru Millésimé 2008,11.0,0,225.0,137.81,6.974951,2475.0,1.725654
1,5892,Champagne,Coteaux Champenois Egly-Ouriet Ambonnay Rouge ...,6.0,98,191.3,116.06,5.754634,1147.8,0.800285
2,4353,Champagne,Champagne Egly-Ouriet Grand Cru Brut Rosé,14.0,127,79.5,45.91,1.706225,1113.0,0.776021
3,5826,Vin,Agnès Levet Côte Rôtie Améthyste 2017,20.0,34,41.2,21.71,0.319337,824.0,0.574521
4,6212,Vin,Domaine des Comtes Lafon Volnay 1er Cru Santen...,7.0,16,115.0,59.42,2.991722,805.0,0.561273
...,...,...,...,...,...,...,...,...,...,...
707,6301,Vin,Borie La Vitarèle Saint-Chinian Midi Rouge 2015,0.0,0,40.5,20.51,0.293989,0.0,0.000000
708,4618,Vin,Alphonse Mellot Sancerre Rouge La Moussière 2014,0.0,0,30.6,16.44,-0.064501,0.0,0.000000
709,5932,Cognac,Cognac Normandin Mercier VFC,0.0,13,59.9,27.18,0.996486,0.0,0.000000
710,4065,Vin,Oratoire Saint Martin Cairanne Rouge Les Douye...,0.0,0,19.5,9.67,-0.466445,0.0,0.000000
711,4198,Vin,Moulin de Gassac IGP Pays d'Hérault Guilhem Ro...,0.0,0,5.8,2.97,-0.962538,0.0,0.000000

In [21]:
#Créer une colonne réalisant la somme cumulative de la colonne précedemment créée
df_merge['%CA_cumule'] = df_merge['%CA'].cumsum()
df_merge

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price,z__score,CA,%CA,%CA_cumule
0,4352,Champagne,Champagne Egly-Ouriet Grand Cru Millésimé 2008,11.0,0,225.0,137.81,6.974951,2475.0,1.725654,1.725654
1,5892,Champagne,Coteaux Champenois Egly-Ouriet Ambonnay Rouge ...,6.0,98,191.3,116.06,5.754634,1147.8,0.800285,2.525939
2,4353,Champagne,Champagne Egly-Ouriet Grand Cru Brut Rosé,14.0,127,79.5,45.91,1.706225,1113.0,0.776021,3.301960
3,5826,Vin,Agnès Levet Côte Rôtie Améthyste 2017,20.0,34,41.2,21.71,0.319337,824.0,0.574521,3.876481
4,6212,Vin,Domaine des Comtes Lafon Volnay 1er Cru Santen...,7.0,16,115.0,59.42,2.991722,805.0,0.561273,4.437754
...,...,...,...,...,...,...,...,...,...,...,...
707,6301,Vin,Borie La Vitarèle Saint-Chinian Midi Rouge 2015,0.0,0,40.5,20.51,0.293989,0.0,0.000000,100.000000
708,4618,Vin,Alphonse Mellot Sancerre Rouge La Moussière 2014,0.0,0,30.6,16.44,-0.064501,0.0,0.000000,100.000000
709,5932,Cognac,Cognac Normandin Mercier VFC,0.0,13,59.9,27.18,0.996486,0.0,0.000000,100.000000
710,4065,Vin,Oratoire Saint Martin Cairanne Rouge Les Douye...,0.0,0,19.5,9.67,-0.466445,0.0,0.000000,100.000000
711,4198,Vin,Moulin de Gassac IGP Pays d'Hérault Guilhem Ro...,0.0,0,5.8,2.97,-0.962538,0.0,0.000000,100.000000

In [22]:
#Grâce aux deux colonnes créées précedemment, calculer le nombre d'articles représentant 80% du CA
len(df_merge[df_merge['%CA_cumule'] <= 80])

432

In [23]:
#Afficher la proportion que représente ce groupe d'articles dans le catalogue entier du site web
print(f"La proportion d'articles représentant 80% du CA est de {100 * len(df_merge[df_merge['%CA_cumule'] <= 80]) / len(df_merge['%CA_cumule']):.2f} %.")

La proportion d'articles représentant 80% du CA est de 60.67 %.

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.2 - Analyse des ventes en quantité</h3>
</div>

In [24]:
#####################################
# Palmarès des articles en quantité #
#####################################

#Effectuer le tri dans l'ordre décroissant de quantités vendues du dataset df_merge
df_merge = df_merge.sort_values(by='total_sales', ascending=False)
df_merge['total_sales']

60     36.0
142    27.0
55     24.0
124    22.0
12     22.0
       ...
707     0.0
708     0.0
709     0.0
710     0.0
711     0.0
Name: total_sales, Length: 712, dtype: float64

In [25]:
#Réinitialiser l'index du dataset par un reset_index
df_merge = df_merge.reset_index(drop=True)

In [26]:
#Afficher les 20 premiers articles en quantité
df_top_qty = df_merge.head(20)

In [27]:
df_merge['total_sales'].sum()

np.float64(5730.0)

In [28]:
#Graphique en barre des 20 premiers articles avec plotly express
fig = px.bar(df_top_qty, 
             x='total_sales', 
             y='post_title', 
             color = 'product_type',
             hover_data="post_title",
             width=1500,
             height=2000,
             title="Top 20 des articles par quantités vendues",
             labels={'total_sales': 'Quantités', 'post_title': 'Nom du produit'})

fig.update_layout(yaxis={'categoryorder':'total ascending'}, 
                  height=800)

fig.show()

In [29]:
#############################
# Calculer le 20 / 80 en quantité #
#############################

#Créer une colonne calculant la part en quantité de la ligne dans le dataset
df_merge['%qty'] = 100 * (df_merge['total_sales'] / df_merge['total_sales'].sum())
df_merge

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price,z__score,CA,%CA,%CA_cumule,%qty
0,4867,Vin,Château De La Selve IGP Coteaux de l'Ardèche M...,36.0,121,9.9,4.86,-0.814072,356.4,0.248494,22.840057,0.628272
1,4203,Vin,Mas Laval IGP Pays d'Hérault Les Pampres Blanc...,27.0,74,9.9,5.01,-0.814072,267.3,0.186371,40.310924,0.471204
2,4275,Vin,I Fabbri Chianti Classico Lamole 2017,24.0,62,14.9,7.78,-0.633017,357.6,0.249331,21.596052,0.418848
3,4726,Vin,François Baur Pinot Noir Schlittweg 2017,22.0,0,12.7,6.82,-0.712681,279.4,0.194807,36.873073,0.383944
4,4647,Vin,Bernard Baudry Chinon Rouge La Croix Boissée 2017,22.0,45,28.5,14.14,-0.140545,627.0,0.437166,8.238934,0.383944
...,...,...,...,...,...,...,...,...,...,...,...,...
707,6301,Vin,Borie La Vitarèle Saint-Chinian Midi Rouge 2015,0.0,0,40.5,20.51,0.293989,0.0,0.000000,100.000000,0.000000
708,4618,Vin,Alphonse Mellot Sancerre Rouge La Moussière 2014,0.0,0,30.6,16.44,-0.064501,0.0,0.000000,100.000000,0.000000
709,5932,Cognac,Cognac Normandin Mercier VFC,0.0,13,59.9,27.18,0.996486,0.0,0.000000,100.000000,0.000000
710,4065,Vin,Oratoire Saint Martin Cairanne Rouge Les Douye...,0.0,0,19.5,9.67,-0.466445,0.0,0.000000,100.000000,0.000000
711,4198,Vin,Moulin de Gassac IGP Pays d'Hérault Guilhem Ro...,0.0,0,5.8,2.97,-0.962538,0.0,0.000000,100.000000,0.000000

In [30]:
#Créer une colonne réalisant la somme cumulative de la colonne précedemment créée
df_merge['%qty_cumule'] = df_merge['%qty'].cumsum()
df_merge

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price,z__score,CA,%CA,%CA_cumule,%qty,%qty_cumule
0,4867,Vin,Château De La Selve IGP Coteaux de l'Ardèche M...,36.0,121,9.9,4.86,-0.814072,356.4,0.248494,22.840057,0.628272,0.628272
1,4203,Vin,Mas Laval IGP Pays d'Hérault Les Pampres Blanc...,27.0,74,9.9,5.01,-0.814072,267.3,0.186371,40.310924,0.471204,1.099476
2,4275,Vin,I Fabbri Chianti Classico Lamole 2017,24.0,62,14.9,7.78,-0.633017,357.6,0.249331,21.596052,0.418848,1.518325
3,4726,Vin,François Baur Pinot Noir Schlittweg 2017,22.0,0,12.7,6.82,-0.712681,279.4,0.194807,36.873073,0.383944,1.902269
4,4647,Vin,Bernard Baudry Chinon Rouge La Croix Boissée 2017,22.0,45,28.5,14.14,-0.140545,627.0,0.437166,8.238934,0.383944,2.286213
...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,6301,Vin,Borie La Vitarèle Saint-Chinian Midi Rouge 2015,0.0,0,40.5,20.51,0.293989,0.0,0.000000,100.000000,0.000000,100.000000
708,4618,Vin,Alphonse Mellot Sancerre Rouge La Moussière 2014,0.0,0,30.6,16.44,-0.064501,0.0,0.000000,100.000000,0.000000,100.000000
709,5932,Cognac,Cognac Normandin Mercier VFC,0.0,13,59.9,27.18,0.996486,0.0,0.000000,100.000000,0.000000,100.000000
710,4065,Vin,Oratoire Saint Martin Cairanne Rouge Les Douye...,0.0,0,19.5,9.67,-0.466445,0.0,0.000000,100.000000,0.000000,100.000000
711,4198,Vin,Moulin de Gassac IGP Pays d'Hérault Guilhem Ro...,0.0,0,5.8,2.97,-0.962538,0.0,0.000000,100.000000,0.000000,100.000000

In [31]:
#Grâce aux deux colonnes créées précedemment, calculer le nombre d'articles représentant 80% des ventes en quantité
len(df_merge[df_merge['%qty_cumule'] <= 80])

431

In [32]:
#Afficher la proportion que représente ce groupe d'articles dans le catalogue entier du site web
print(f"La proportion d'articles représentant 80% du CA est de {100 * len(df_merge[df_merge['%qty_cumule'] <= 80]) / len(df_merge['%qty_cumule']):.2f} %.")

La proportion d'articles représentant 80% du CA est de 60.53 %.

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.3 - Analyse des stocks</h3>
</div>

In [33]:
######################################
# Calculer le nombre de mois de stock #
######################################

#Import de numpy 
import numpy as np
#Création de la colonne Rotation de stock
df_merge['rotation_stock'] = df_merge['stock_quantity'] / df_merge['total_sales']
df_merge['rotation_stock'].describe()

/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/pandas/core/nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    690.000000
mean            inf
std             NaN
min        0.000000
25%        1.750000
50%        2.408333
75%        3.097727
max             inf
Name: rotation_stock, dtype: float64

In [34]:
#Remplacement des "inf" par 0
df_merge['rotation_stock'] = df_merge['rotation_stock'].replace(np.inf, 0)
df_merge['rotation_stock']= df_merge['rotation_stock'].fillna(0)

In [35]:
#Effectuer le tri dans l'ordre décroissant du nombre de mois de stock dans le dataset df_merge
df_merge = df_merge.sort_values(by='rotation_stock', ascending=False).reset_index(drop=True)
df_merge['rotation_stock']

0      31.250000
1      27.600000
2      27.000000
3      25.000000
4      23.666667
         ...
707     0.000000
708     0.000000
709     0.000000
710     0.000000
711     0.000000
Name: rotation_stock, Length: 712, dtype: float64

In [36]:
#Graphique en barre du flop 20 des produits qui ont le plus de mois de stock
flop_20 = df_merge.head(20)

fig = px.bar(flop_20, 
             x='rotation_stock', 
             y='post_title', 
             color='product_type',
             hover_data="post_title",
             width=1500,
             height=2000,
             title="Flop 20 des produits qui ont le plus de mois de stocks",
             labels={'rotation_stock': 'Mois de stocks', 'post_title': 'Nom du produit'})

fig.update_layout(yaxis={'categoryorder':'total ascending'}, 
                  height=800)

fig.show()

In [37]:
####################################
# Valorisation des stocks en euros #
####################################

#Création de la colonne Valorisation des stocks en euros
df_merge['valorisation_euros'] = df_merge['stock_quantity'] * df_merge['price']

In [38]:
df_merge['valorisation_euros']

0       6625.0
1      18630.0
2       4179.6
3       7375.0
4       2662.5
        ...
707        0.0
708        0.0
709        0.0
710        0.0
711        0.0
Name: valorisation_euros, Length: 712, dtype: float64

In [39]:
#Calculer la somme de la colonne "Valorisation_stock_euros"
print(f"La valeur totale du stock est de {df_merge['valorisation_euros'].sum():,.2f} €.")

La valeur totale du stock est de 493,871.50 €.

In [40]:
##############################################
# Valorisation du nombre de produits en stock #
##############################################

#Calculer la somme de la colonne stock quantity
print(f"La nombre de produits en stock est de {df_merge['stock_quantity'].sum()} bouteilles.")

La nombre de produits en stock est de 16684 bouteilles.

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.4 - Analyse du taux de marge</h3>
</div>

In [41]:
############################
# Analyse du taux de marge #
############################

#Création de la colonne Prix HT
tva = 0.20 
df_merge['prix_ht'] = df_merge['price'] / (1 + tva)

[Source](https://entreprendre.service-public.gouv.fr/vosdroits/F32101) TVA sur les boissons

In [42]:
#Création de la colonne Taux de marge
df_merge['marge'] = df_merge['prix_ht'] - df_merge['purchase_price']

In [43]:
df_merge['taux_marge'] = (df_merge['marge']/df_merge['prix_ht']) * 100

In [44]:
#Afficher le prix minimum de la colonne "taux_marge"
print(f"Le taux de marge minimum est de {df_merge['taux_marge'].min():.2f}%.")

Le taux de marge minimum est de -634.99%.

In [45]:
#Afficher le prix maximum de la colonne "taux_marge"
print(f"Le taux de marge maximum est de {df_merge['taux_marge'].max():.2f}%.")

Le taux de marge maximum est de 47.76%.

In [46]:
#Affichage de la ligne avec un taux de marge inférieur à 0
df_marge_neg = df_merge[df_merge['taux_marge'] < 0]
df_marge_neg

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price,z__score,CA,%CA,%CA_cumule,%qty,%qty_cumule,rotation_stock,valorisation_euros,prix_ht,marge,taux_marge
664,4355,Champagne,Champagne Egly-Ouriet Grand Cru Blanc de Noirs,0.0,97,12.65,77.48,-0.714492,0.0,0.0,100.0,0.0,100.0,0.0,1227.05,10.541667,-66.938333,-634.988142

In [47]:
#probablement une virgule mal placée, le vrai prix doit être 126.5€

In [48]:
#Création d'un dataframe avec les taux positifs
df_benef = df_merge[df_merge['taux_marge'] > 0]

In [49]:
#Afficher le prix minimum de la colonne "taux_marge".
print(f"Le taux de marge minimum est de {df_benef['taux_marge'].min():.2f}%.")

Le taux de marge minimum est de 22.78%.

In [50]:
#Afficher le prix maximum de la colonne "taux_marge"
print(f"Le taux de marge maximum est de {df_benef['taux_marge'].max():.2f}%.")

Le taux de marge maximum est de 47.76%.

In [51]:
df_benef['benef_net'] = (df_benef['taux_marge'] * df_benef['CA']) /100

In [52]:
#Création d'un dataframe avec le taux de marge moyen par type de produit
df_marge_par_type = df_benef.groupby('product_type')['taux_marge'].mean().reset_index()

In [53]:
df_marge_par_type.rename(columns={'taux_marge': 'taux_marge_moyenne'}, inplace=True)
df_marge_par_type= df_marge_par_type.sort_values(by='taux_marge_moyenne', ascending=False)
df_marge_par_type

    product_type  taux_marge_moyenne
1         Cognac           45.067614
5         Whisky           44.918865
2            Gin           42.800000
4            Vin           38.016165
0      Champagne           28.488539
3  Huile d'olive           24.998198

In [54]:
#Affichage dans un graphique du taux de marge par type de produit

fig = px.bar(df_marge_par_type, 
             x='product_type', 
             y='taux_marge_moyenne', 
             color='product_type',
             hover_data=["product_type"],
             width=1000,
             height=500,
             title="Taux de marge moyen par type de produit",
             labels={'marge_moyenne': 'Marge_moyenne', 'product_type': 'Type de produit'})

fig.update_layout(yaxis={'categoryorder':'total ascending'}, 
                 height=600)

fig.show()

In [55]:
#création d'un dataset avec la somme de bénéfices par type de produit
df_somme_benef_par_type = df_benef.groupby('product_type')['benef_net'].sum().reset_index()

In [56]:
# affichage en diagramme à barres 

fig = px.bar(df_somme_benef_par_type, 
             x='product_type', 
             y='benef_net', 
             color='product_type',
             hover_data=["product_type"],
             text='benef_net',
             width=1000,
             height=500,
             title="Somme des bénéfices par type de produit",
             labels={'benef_net': 'Bénéfices moyen', 'product_type': 'Type de produit'})

fig.update_traces(texttemplate='%{text:.2f} €', textposition='outside')

fig.update_layout(yaxis={'categoryorder':'total ascending'}, 
                 height=600)

fig.show()

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.5 - Analyse des corrélations entre les variables stock, sales et price</h3>
</div>

In [57]:
############################
# Analyse des correlations #
############################

# Creation d'une heatmap de correlation avec les variables stock, sales et price (version Plotly)

corr = df_merge[['stock_quantity', 'total_sales', 'price']].corr()

fig = px.imshow(
    corr,
    text_auto=".2f",
    color_continuous_scale="RdBu_r",
    zmin=-1, zmax=1,
    title="Matrice de correlation"
)
fig.update_layout(width=500, height=450)
fig.show()

In [58]:
corr

                stock_quantity  total_sales     price
stock_quantity        1.000000     0.438766 -0.106168
total_sales           0.438766     1.000000 -0.515546
price                -0.106168    -0.515546  1.000000

In [59]:
# Version "demi-heatmap" avec Plotly : le triangle superieur est masque (valeurs mises a NaN)

mask = np.triu(np.ones_like(corr, dtype=bool))
corr_masked = corr.mask(mask)

fig = px.imshow(
    corr_masked,
    text_auto=".2f",
    color_continuous_scale="RdBu_r",
    zmin=-1, zmax=1,
    title="Matrice de correlation (demi)"
)
fig.update_layout(width=500, height=450)
fig.show()

In [60]:
# Idem en ajoutant la variable marge

corr = df_merge[['stock_quantity', 'total_sales', 'price', 'marge']].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
corr_masked = corr.mask(mask)

fig = px.imshow(
    corr_masked,
    text_auto=".2f",
    color_continuous_scale="RdBu_r",
    zmin=-1, zmax=1,
    title="Matrice de correlation (demi)"
)
fig.update_layout(width=500, height=450)
fig.show()

In [61]:
#Que peut-on conclure des corrélations ?

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.6 - Mise à disposition de la nouvelle table sur un fichier Excel</h3>
</div>

In [62]:
#Mettre le dataset df_merge sur un fichier Excel
#Cette étape peut être utile pour partager le résultat du dataset obtenu avec les équipes.  
df_merge.to_excel("Analyse_Bottleneck_Finale.xlsx", index=False)

print("Le fichier a été exporté avec succès !")

Le fichier a été exporté avec succès !

# Essai Plotly pour visualisation

In [67]:
import plotly.graph_objects as go

df_merge['cout_achat_total'] = df_merge['purchase_price'] * df_merge['total_sales']
df_merge['tva_total'] = df_merge['CA'] - (df_merge['CA'] / (1 + tva))
df_merge['ca_ht_total'] = df_merge['CA'] / (1 + tva)
df_merge['benefice_total'] = df_merge['ca_ht_total'] - df_merge['cout_achat_total']

composantes = ['cout_achat_total', 'tva_total', 'benefice_total']
couleurs = {
    'cout_achat_total': '#0072B2',   # bleu
    'tva_total': '#E69F00',          # orange/ambre
    'benefice_total': '#009E73'      # vert bleuté (teal), distinct du bleu même en daltonisme
}

def agreger(df, niveau):
    return df.groupby(niveau, as_index=False)[composantes].sum()

df_cat = agreger(df_merge, 'product_type')
categories = df_merge['product_type'].unique()

# Une trace par composante (empilement), initialisée sur la vue "toutes catégories"
fig = go.Figure()
for comp in composantes:
    fig.add_trace(go.Bar(
        name=comp, x=df_cat['product_type'], y=df_cat[comp],
        marker_color=couleurs[comp]
    ))
fig.update_layout(barmode='stack', title="CA par catégorie : coût d'achat / TVA / bénéfice")

# Précalcul de toutes les combinaisons (niveau x tri)
buttons = []

def make_args(df, x_col, sort_by):
    df_sorted = df.sort_values(sort_by, ascending=False)
    return {"x": [df_sorted[x_col]] * 3,
            "y": [df_sorted[c] for c in composantes]}

for sort_by in composantes:
    buttons.append(dict(
        label=f"Toutes catégories — triées par {sort_by}",
        method="update",
        args=[make_args(df_cat, 'product_type', sort_by)]
    ))

for cat in categories:
    df_prod = agreger(df_merge[df_merge['product_type'] == cat], 'post_title')
    for sort_by in composantes:
        buttons.append(dict(
            label=f"{cat} — triée par {sort_by}",
            method="update",
            args=[make_args(df_prod, 'post_title', sort_by)]
        ))

fig.update_layout(updatemenus=[dict(active=0, buttons=buttons, x=1.3, y=1, xanchor='left')])
fig.show()

Essai concluant avec la possibilité de comparer les catégories entre elles et de regarder à l'intérieur de la catégorie les top/flops sur un seul graphique.

# Essais Altair pour visualisation

In [72]:
import altair as alt

df_long = df_merge.groupby('product_type', as_index=False)[['cout_achat_total','tva_total','benefice_total']].sum()
df_long = df_long.melt(id_vars='product_type', var_name='composante', value_name='montant')

dropdown = alt.binding_select(options=sorted(df_merge['product_type'].unique()), name='Catégorie : ')
selection = alt.selection_point(fields=['product_type'], bind=dropdown)

chart = alt.Chart(df_long).mark_bar().encode(
    x='product_type:N',
    y='sum(montant):Q',
    color=alt.Color('composante:N', scale=alt.Scale(
        domain=['cout_achat_total','tva_total','benefice_total'],
        range=['#0072B2','#E69F00','#009E73']))
).add_params(selection).transform_filter(selection)

chart

alt.Chart(...)

Graphique peu lisible et impossibilité de voir à l'échelle des produits.

In [71]:
df_produits_long = df_merge[['product_type', 'post_title', 'cout_achat_total', 'tva_total', 'benefice_total']].melt(
    id_vars=['product_type', 'post_title'], var_name='composante', value_name='montant'
)

dropdown_cat = alt.binding_select(options=sorted(df_merge['product_type'].dropna().unique()), name='Catégorie : ')
selection_cat = alt.selection_point(fields=['product_type'], bind=dropdown_cat)

chart = alt.Chart(df_produits_long).mark_bar().encode(
    x=alt.X('post_title:N', title='Produit', sort='-y'),   # tri décroissant par montant total (fixe pour l'instant)
    y=alt.Y('sum(montant):Q', title='Montant (€)'),
    color=alt.Color('composante:N', scale=alt.Scale(
        domain=['cout_achat_total', 'tva_total', 'benefice_total'],
        range=['#0072B2', '#E69F00', '#009E73'])),
    tooltip=['post_title', 'composante', 'montant']
).add_params(selection_cat).transform_filter(selection_cat).properties(
    width=700, height=450,
    title="Détail par produit — coût d'achat / TVA / bénéfice"
)
chart

alt.Chart(...)

Même constat que pour grahioque précédent mais inversé.

Conclusion : Altair n'est pas capable de faire ce que l'on souhaite.

# Essai script Claude

In [73]:
from consolidation_donnees import consolider_donnees, afficher_rapport

df_merge, rapport = consolider_donnees("erp.xlsx", "web.xlsx", "liaison.xlsx")
afficher_rapport(rapport)
df_merge

/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

=== Rapport de consolidation des données Bottleneck ===
- erp prix negatifs supprimes : 3
- erp stocks negatifs corriges : 2
- erp hors vente exclus : 106
- erp doublons product id : 0
- web sku manquants exclus : 85
- web lignes non product exclues : 714
- web product type manquant exclus : 1
- web doublons sku : 0
- liaison doublons product id : 0
- liaison doublons id web : 0
- liaison id web manquants : 91
- product id dans liaison absents erp : 109
- product id dans erp absents liaison : 0
- id web dans web absents merge : 1
- id web dans merge absents web : 2
- lignes finales consolidees : 712

/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,product_id,product_type,post_title,total_sales,stock_quantity,price,purchase_price
0,5794,Vin,Château Fonréaud Bordeaux Blanc Le Cygne 2016,5.0,15,21.70,10.65
1,5827,Vin,Agnès Levet Côte Rôtie Maestria 2017,2.0,4,55.00,29.55
2,4964,Vin,Château Turcaud Bordeaux Rouge Cuvée Majeure 2018,10.0,23,12.10,6.50
3,4223,Vin,Xavier Frissant Touraine Sauvignon 2019,15.0,42,9.70,4.81
4,5900,Vin,Stéphane Tissot Arbois D.D. 2016,7.0,21,18.25,8.96
...,...,...,...,...,...,...,...
707,4073,Vin,Château de Vaudieu Châteauneuf-du-Pape L'Avenu...,4.0,8,77.80,40.60
708,4198,Vin,Moulin de Gassac IGP Pays d'Hérault Guilhem Ro...,0.0,0,5.80,2.97
709,5630,Vin,Parés Baltà Penedès Electio 2013,10.0,23,28.00,14.61
710,5962,Vin,Camin Larredya Jurançon Moelleux Au Capcéu 2018,5.0,8,30.00,15.50
711,4261,Vin,Chermette Domaine du Vissoux Beaujolais Griott...,15.0,48,9.90,5.01

# Essai script VsCode

In [74]:
from notebook_api import consolidate_files

consolidated_df, report = consolidate_files(
    erp='erp.xlsx',
    web='web.xlsx',
    liaison='liaison.xlsx',
    out_dir='results',      # optionnel
    write_outputs=False     # True pour écrire les fichiers
)

consolidated_df.info()

/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

<class 'pandas.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      712 non-null    int64
 1   price           712 non-null    float64
 2   purchase_price  712 non-null    float64
 3   stock_quantity  712 non-null    int64
 4   stock_status    712 non-null    str
 5   id_web          712 non-null    str
 6   sku             712 non-null    str
 7   post_title      712 non-null    str
 8   tax_status      712 non-null    str
 9   total_sales     712 non-null    float64
 10  product_type    712 non-null    str
dtypes: float64(3), int64(2), str(6)
memory usage: 61.3 KB

/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/home/zied/Documents/Cours-OC/venv/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [75]:
for k, v in report.items():
    print(f"{k}: {v}")

initial_rows_erp: 825
excluded_price_negative: 3
corrected_stock_negative_to_zero: 2
excluded_onsale_web: 106
duplicates_removed_erp: 0
recalculated_stock_status_changed: 2
initial_rows_web: 1513
excluded_missing_sku: 85
excluded_post_type_not_product: 714
excluded_missing_product_type: 1
duplicates_removed_web: 0
erp_without_liaison_matches: 3
erp_liaison_matched_rows: 713
erp_web_unmatched_after_join: 1
final_consolidated_rows: 712